# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\InterfacesRaw\Carga.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(492, 158)
        Dialog.setMaximumSize(QtCore.QSize(686, 203))
        Dialog.setStyleSheet("#Dialog{\n"
"    background-color: #f0ecec;\n"
"    border-radious: 8px;\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 13)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imagen = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagen.sizePolicy().hasHeightForWidth())
        self.imagen.setSizePolicy(sizePolicy)
        self.imagen.setMaximumSize(QtCore.QSize(96, 80))
        self.imagen.setStyleSheet("")
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.verticalLayout.addWidget(self.imagen, 0, QtCore.Qt.AlignHCenter)
        self.Texto = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.Texto.setFont(font)
        self.Texto.setStyleSheet("")
        self.Texto.setObjectName("Texto")
        self.verticalLayout.addWidget(self.Texto, 0, QtCore.Qt.AlignHCenter)
        self.Porcentaje = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Porcentaje.setFont(font)
        self.Porcentaje.setObjectName("Porcentaje")
        self.verticalLayout.addWidget(self.Porcentaje, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.setStretch(0, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.imagen.setText(_translate("Dialog", "TextLabel"))
        self.Texto.setText(_translate("Dialog", "TextLabel"))
        self.Porcentaje.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
